fix yaml syntax

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,16 +16,16 @@ jobs:
 
     steps:
       - name: Check Secrets
-      run: |
-        secretList=("GITHUB_TOKEN" "APPLE_CERTIFICATE" "APPLE_CERTIFICATE_PASSWORD" "APPLE_SIGNING_IDENTITY" "APPLE_ID" "APPLE_PASSWORD" "APPLE_TEAM_ID")
-        for secret in ${secretList[@]}; do
-          if [[ -z "${{ secrets[$secret] }}" ]]; then
-          echo "Missing secret $secret"
-          exit 1
-          fi
-        done
-        echo "All secrets exist"
-      shell: bash
+        run: |
+          secretList=("GITHUB_TOKEN" "APPLE_CERTIFICATE" "APPLE_CERTIFICATE_PASSWORD" "APPLE_SIGNING_IDENTITY" "APPLE_ID" "APPLE_PASSWORD" "APPLE_TEAM_ID")
+          for secret in ${secretList[@]}; do
+            if [[ -z "${{ secrets[$secret] }}" ]]; then
+            echo "Missing secret $secret"
+            exit 1
+            fi
+          done
+          echo "All secrets exist"
+        shell: bash
 
       - name: Checkout repository
         uses: actions/checkout@v3
